language: generic
sudo: required
services:
  - docker
jobs:
  include:
    - stage: Verify Login Credentials
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin