language: generic
sudo: required
services: 
  -  docker
before_install:
  - docker build -t areorrtwetb/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true areorrtwetb/react-test npm run test -- --coverage
after_success:
  - docker build -t areorrtwetb/multi-client ./client
  - docker build -t areorrtwetb/multi-nginx ./nginx
  - docker build -t areorrtwetb/multi-server ./server
  - docker build -t areorrtwetb/multi-worker ./worker
  #LOG IN THE docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  #Take those iages aand push them to docker hub
  - docker push areorrtwetb/multi-client
  - docker push areorrtwetb/multi-nginx
  - docker push areorrtwetb/multi-server
  - docker push areorrtwetb/multi-worker
